/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/[team]/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as TeamBlogIndexRouteImport } from './routes/[team]/[blog]/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as TeamBlogSlugIndexRouteImport } from './routes/[team]/[blog]/[slug]/index'
import { Route as TeamBlogAdminIndexRouteImport } from './routes/[team]/[blog]/admin/index'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as TeamBlogAdminPostsNewRouteImport } from './routes/[team]/[blog]/admin/posts/new'
import { Route as TeamBlogAdminPostsEnhancedNewRouteImport } from './routes/[team]/[blog]/admin/posts/enhanced-new'
import { Route as TeamBlogAdminPostsCollaborativeRouteImport } from './routes/[team]/[blog]/admin/posts/collaborative'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamBlogIndexRoute = TeamBlogIndexRouteImport.update({
  id: '/team/blog/',
  path: '/team/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamBlogSlugIndexRoute = TeamBlogSlugIndexRouteImport.update({
  id: '/team/blog/slug/',
  path: '/team/blog/slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamBlogAdminIndexRoute = TeamBlogAdminIndexRouteImport.update({
  id: '/team/blog/admin/',
  path: '/team/blog/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamBlogAdminPostsNewRoute = TeamBlogAdminPostsNewRouteImport.update({
  id: '/team/blog/admin/posts/new',
  path: '/team/blog/admin/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamBlogAdminPostsEnhancedNewRoute =
  TeamBlogAdminPostsEnhancedNewRouteImport.update({
    id: '/team/blog/admin/posts/enhanced-new',
    path: '/team/blog/admin/posts/enhanced-new',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamBlogAdminPostsCollaborativeRoute =
  TeamBlogAdminPostsCollaborativeRouteImport.update({
    id: '/team/blog/admin/posts/collaborative',
    path: '/team/blog/admin/posts/collaborative',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/team/': typeof TeamIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/team/blog/': typeof TeamBlogIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/team/blog/admin/': typeof TeamBlogAdminIndexRoute
  '/team/blog/slug/': typeof TeamBlogSlugIndexRoute
  '/team/blog/admin/posts/collaborative': typeof TeamBlogAdminPostsCollaborativeRoute
  '/team/blog/admin/posts/enhanced-new': typeof TeamBlogAdminPostsEnhancedNewRoute
  '/team/blog/admin/posts/new': typeof TeamBlogAdminPostsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/team': typeof TeamIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/team/blog': typeof TeamBlogIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/team/blog/admin': typeof TeamBlogAdminIndexRoute
  '/team/blog/slug': typeof TeamBlogSlugIndexRoute
  '/team/blog/admin/posts/collaborative': typeof TeamBlogAdminPostsCollaborativeRoute
  '/team/blog/admin/posts/enhanced-new': typeof TeamBlogAdminPostsEnhancedNewRoute
  '/team/blog/admin/posts/new': typeof TeamBlogAdminPostsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/team/': typeof TeamIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/team/blog/': typeof TeamBlogIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/team/blog/admin/': typeof TeamBlogAdminIndexRoute
  '/team/blog/slug/': typeof TeamBlogSlugIndexRoute
  '/team/blog/admin/posts/collaborative': typeof TeamBlogAdminPostsCollaborativeRoute
  '/team/blog/admin/posts/enhanced-new': typeof TeamBlogAdminPostsEnhancedNewRoute
  '/team/blog/admin/posts/new': typeof TeamBlogAdminPostsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/team/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/team/blog/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/team/blog/admin/'
    | '/team/blog/slug/'
    | '/team/blog/admin/posts/collaborative'
    | '/team/blog/admin/posts/enhanced-new'
    | '/team/blog/admin/posts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/team'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/team/blog'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/team/blog/admin'
    | '/team/blog/slug'
    | '/team/blog/admin/posts/collaborative'
    | '/team/blog/admin/posts/enhanced-new'
    | '/team/blog/admin/posts/new'
  id:
    | '__root__'
    | '/'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/team/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/team/blog/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/team/blog/admin/'
    | '/team/blog/slug/'
    | '/team/blog/admin/posts/collaborative'
    | '/team/blog/admin/posts/enhanced-new'
    | '/team/blog/admin/posts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  TeamIndexRoute: typeof TeamIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  TeamBlogIndexRoute: typeof TeamBlogIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
  TeamBlogAdminIndexRoute: typeof TeamBlogAdminIndexRoute
  TeamBlogSlugIndexRoute: typeof TeamBlogSlugIndexRoute
  TeamBlogAdminPostsCollaborativeRoute: typeof TeamBlogAdminPostsCollaborativeRoute
  TeamBlogAdminPostsEnhancedNewRoute: typeof TeamBlogAdminPostsEnhancedNewRoute
  TeamBlogAdminPostsNewRoute: typeof TeamBlogAdminPostsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/blog/': {
      id: '/team/blog/'
      path: '/team/blog'
      fullPath: '/team/blog/'
      preLoaderRoute: typeof TeamBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/blog/slug/': {
      id: '/team/blog/slug/'
      path: '/team/blog/slug'
      fullPath: '/team/blog/slug/'
      preLoaderRoute: typeof TeamBlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/blog/admin/': {
      id: '/team/blog/admin/'
      path: '/team/blog/admin'
      fullPath: '/team/blog/admin/'
      preLoaderRoute: typeof TeamBlogAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/blog/admin/posts/new': {
      id: '/team/blog/admin/posts/new'
      path: '/team/blog/admin/posts/new'
      fullPath: '/team/blog/admin/posts/new'
      preLoaderRoute: typeof TeamBlogAdminPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/blog/admin/posts/enhanced-new': {
      id: '/team/blog/admin/posts/enhanced-new'
      path: '/team/blog/admin/posts/enhanced-new'
      fullPath: '/team/blog/admin/posts/enhanced-new'
      preLoaderRoute: typeof TeamBlogAdminPostsEnhancedNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/blog/admin/posts/collaborative': {
      id: '/team/blog/admin/posts/collaborative'
      path: '/team/blog/admin/posts/collaborative'
      fullPath: '/team/blog/admin/posts/collaborative'
      preLoaderRoute: typeof TeamBlogAdminPostsCollaborativeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  TeamIndexRoute: TeamIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  TeamBlogIndexRoute: TeamBlogIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
  TeamBlogAdminIndexRoute: TeamBlogAdminIndexRoute,
  TeamBlogSlugIndexRoute: TeamBlogSlugIndexRoute,
  TeamBlogAdminPostsCollaborativeRoute: TeamBlogAdminPostsCollaborativeRoute,
  TeamBlogAdminPostsEnhancedNewRoute: TeamBlogAdminPostsEnhancedNewRoute,
  TeamBlogAdminPostsNewRoute: TeamBlogAdminPostsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
